---

publicEndpoint:
  /v1/users/login/email
  /v1/users/securegroup

groups:
  default: guest
  defaultOauth: member
  guest:
    User:
      v1:index|logout
  administrator:
    User:
      v1:index|*
